export const DEFAULT_CONFIG = {
  api: 'browser',
  controller_port: 8080,
  client_port: 80,
  azure_subscription_key: '',
  azure_region: '',
  language: 'en-US',
  speechly_app: '',
  topic: '',
  font_size: 20,
  max_lines: -1,
  clear_temp_on_stop: false,
  azure_endpoint_id: '',
  word_filter: true,
  all_caps: false,
};
